# fly.toml file generated for open-cmap on 2023-04-03T10:06:44+07:00

app = "open-cmap"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[build]
  [build.args]
    NODE_VERSION = "19"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_URL = "https://open-cmap.fly.dev/"
  APP_NAME = "Open-CMAP"
  DB_CONNECTION = "pgsql"
  MAIL_DRIVER=smtp
  MAIL_HOST="smtp.gmail.com"
  MAIL_PORT="465"
  MAIL_USERNAME="zakacoding@gmail.com"
  MAIL_PASSWORD="qxtgdvljkzkhyoqh"
  MAIL_ENCRYPTION="ssl"
  MAIL_FROM_ADDRESS="open-cmap-noreply@opencmap.io"
  MAIL_FROM_NAME="${APP_NAME}"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
